[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
base58 = "0.2.0"
signature = "2.3.0-pre.4"
solana-sdk = "2.1.12"
solana-client = "2.1.12"
solana-program = "2.1.12"
solana-account-decoder = "2.1.12"
solana-transaction-status = "2.1.12"